language: java
jdk:
  - openjdk8
branches:
  only:
    - master

before_install:
  - chmod +x mvnw

cache:
  directories:
    - '$HOME/.m2'

env:
  matrix:
    - CONFIG_IMAGE=bhhan87/bhhan-config:chapter3
    - LICENSE_IMAGE=bhhan87/bhhan-licensing-service:chapter2

script: 
    - 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
    - './mvnw clean package docker:build'
    - 'docker push $LICENSE_IMAGE'
    - 'docker push $CONFIG_IMAGE'

notifications:
  email:
    recipients:
      - 'hbh5274@gmail.com'
