management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    data: classpath:import.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true